 
# .github/workflows/magalix.yml
name: Magalix

on:
  push:
    branches: [ main ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Magalix
      uses: magalixcorp/magalix-action@main
      with:
        webhook: ${{ secrets.TEST_GUARD }}
